/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as InvitationIdRouteImport } from './routes/invitation.$id'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppreportsSalesRouteImport } from './routes/_app/(reports)/sales'
import { Route as AppinventoryMotorcyclesIndexRouteImport } from './routes/_app/(inventory)/motorcycles/index'
import { Route as AppinventoryCarsIndexRouteImport } from './routes/_app/(inventory)/cars/index'
import { Route as AppbranchesBranchesIndexRouteImport } from './routes/_app/(branches)/branches.index'
import { Route as AppinventoryMotorcyclesIdRouteImport } from './routes/_app/(inventory)/motorcycles/$id'
import { Route as AppbranchesBranchesIdRouteImport } from './routes/_app/(branches)/branches.$id'
import { Route as AppinventoryCarstabsIdRouteImport } from './routes/_app/(inventory)/cars/(tabs)/$id'
import { Route as AppinventoryCarstabsIdIndexRouteImport } from './routes/_app/(inventory)/cars/(tabs)/$id.index'
import { Route as AppinventoryCarstabsIdServiceHistoryRouteImport } from './routes/_app/(inventory)/cars/(tabs)/$id.service-history'
import { Route as AppinventoryCarstabsIdGalleryRouteImport } from './routes/_app/(inventory)/cars/(tabs)/$id.gallery'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const InvitationIdRoute = InvitationIdRouteImport.update({
  id: '/invitation/$id',
  path: '/invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppreportsSalesRoute = AppreportsSalesRouteImport.update({
  id: '/(reports)/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppinventoryMotorcyclesIndexRoute =
  AppinventoryMotorcyclesIndexRouteImport.update({
    id: '/(inventory)/motorcycles/',
    path: '/motorcycles/',
    getParentRoute: () => AppRoute,
  } as any)
const AppinventoryCarsIndexRoute = AppinventoryCarsIndexRouteImport.update({
  id: '/(inventory)/cars/',
  path: '/cars/',
  getParentRoute: () => AppRoute,
} as any)
const AppbranchesBranchesIndexRoute =
  AppbranchesBranchesIndexRouteImport.update({
    id: '/(branches)/branches/',
    path: '/branches/',
    getParentRoute: () => AppRoute,
  } as any)
const AppinventoryMotorcyclesIdRoute =
  AppinventoryMotorcyclesIdRouteImport.update({
    id: '/(inventory)/motorcycles/$id',
    path: '/motorcycles/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppbranchesBranchesIdRoute = AppbranchesBranchesIdRouteImport.update({
  id: '/(branches)/branches/$id',
  path: '/branches/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppinventoryCarstabsIdRoute = AppinventoryCarstabsIdRouteImport.update({
  id: '/(inventory)/cars/(tabs)/$id',
  path: '/cars/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppinventoryCarstabsIdIndexRoute =
  AppinventoryCarstabsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppinventoryCarstabsIdRoute,
  } as any)
const AppinventoryCarstabsIdServiceHistoryRoute =
  AppinventoryCarstabsIdServiceHistoryRouteImport.update({
    id: '/service-history',
    path: '/service-history',
    getParentRoute: () => AppinventoryCarstabsIdRoute,
  } as any)
const AppinventoryCarstabsIdGalleryRoute =
  AppinventoryCarstabsIdGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AppinventoryCarstabsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/about': typeof PublicAboutRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/': typeof PublicIndexRoute
  '/sales': typeof AppreportsSalesRoute
  '/branches/$id': typeof AppbranchesBranchesIdRoute
  '/motorcycles/$id': typeof AppinventoryMotorcyclesIdRoute
  '/branches': typeof AppbranchesBranchesIndexRoute
  '/cars': typeof AppinventoryCarsIndexRoute
  '/motorcycles': typeof AppinventoryMotorcyclesIndexRoute
  '/cars/$id': typeof AppinventoryCarstabsIdRouteWithChildren
  '/cars/$id/gallery': typeof AppinventoryCarstabsIdGalleryRoute
  '/cars/$id/service-history': typeof AppinventoryCarstabsIdServiceHistoryRoute
  '/cars/$id/': typeof AppinventoryCarstabsIdIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/about': typeof PublicAboutRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/': typeof PublicIndexRoute
  '/sales': typeof AppreportsSalesRoute
  '/branches/$id': typeof AppbranchesBranchesIdRoute
  '/motorcycles/$id': typeof AppinventoryMotorcyclesIdRoute
  '/branches': typeof AppbranchesBranchesIndexRoute
  '/cars': typeof AppinventoryCarsIndexRoute
  '/motorcycles': typeof AppinventoryMotorcyclesIndexRoute
  '/cars/$id/gallery': typeof AppinventoryCarstabsIdGalleryRoute
  '/cars/$id/service-history': typeof AppinventoryCarstabsIdServiceHistoryRoute
  '/cars/$id': typeof AppinventoryCarstabsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/(reports)/sales': typeof AppreportsSalesRoute
  '/_app/(branches)/branches/$id': typeof AppbranchesBranchesIdRoute
  '/_app/(inventory)/motorcycles/$id': typeof AppinventoryMotorcyclesIdRoute
  '/_app/(branches)/branches/': typeof AppbranchesBranchesIndexRoute
  '/_app/(inventory)/cars/': typeof AppinventoryCarsIndexRoute
  '/_app/(inventory)/motorcycles/': typeof AppinventoryMotorcyclesIndexRoute
  '/_app/(inventory)/cars/(tabs)/$id': typeof AppinventoryCarstabsIdRouteWithChildren
  '/_app/(inventory)/cars/(tabs)/$id/gallery': typeof AppinventoryCarstabsIdGalleryRoute
  '/_app/(inventory)/cars/(tabs)/$id/service-history': typeof AppinventoryCarstabsIdServiceHistoryRoute
  '/_app/(inventory)/cars/(tabs)/$id/': typeof AppinventoryCarstabsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/about'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/invitation/$id'
    | '/'
    | '/sales'
    | '/branches/$id'
    | '/motorcycles/$id'
    | '/branches'
    | '/cars'
    | '/motorcycles'
    | '/cars/$id'
    | '/cars/$id/gallery'
    | '/cars/$id/service-history'
    | '/cars/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/about'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/invitation/$id'
    | '/'
    | '/sales'
    | '/branches/$id'
    | '/motorcycles/$id'
    | '/branches'
    | '/cars'
    | '/motorcycles'
    | '/cars/$id/gallery'
    | '/cars/$id/service-history'
    | '/cars/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/onboarding'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/settings'
    | '/_public/about'
    | '/_public/forgot-password'
    | '/_public/sign-in'
    | '/_public/sign-up'
    | '/invitation/$id'
    | '/_public/'
    | '/_app/(reports)/sales'
    | '/_app/(branches)/branches/$id'
    | '/_app/(inventory)/motorcycles/$id'
    | '/_app/(branches)/branches/'
    | '/_app/(inventory)/cars/'
    | '/_app/(inventory)/motorcycles/'
    | '/_app/(inventory)/cars/(tabs)/$id'
    | '/_app/(inventory)/cars/(tabs)/$id/gallery'
    | '/_app/(inventory)/cars/(tabs)/$id/service-history'
    | '/_app/(inventory)/cars/(tabs)/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  InvitationIdRoute: typeof InvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/invitation/$id': {
      id: '/invitation/$id'
      path: '/invitation/$id'
      fullPath: '/invitation/$id'
      preLoaderRoute: typeof InvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(reports)/sales': {
      id: '/_app/(reports)/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppreportsSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(inventory)/motorcycles/': {
      id: '/_app/(inventory)/motorcycles/'
      path: '/motorcycles'
      fullPath: '/motorcycles'
      preLoaderRoute: typeof AppinventoryMotorcyclesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(inventory)/cars/': {
      id: '/_app/(inventory)/cars/'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof AppinventoryCarsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(branches)/branches/': {
      id: '/_app/(branches)/branches/'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppbranchesBranchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(inventory)/motorcycles/$id': {
      id: '/_app/(inventory)/motorcycles/$id'
      path: '/motorcycles/$id'
      fullPath: '/motorcycles/$id'
      preLoaderRoute: typeof AppinventoryMotorcyclesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(branches)/branches/$id': {
      id: '/_app/(branches)/branches/$id'
      path: '/branches/$id'
      fullPath: '/branches/$id'
      preLoaderRoute: typeof AppbranchesBranchesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(inventory)/cars/(tabs)/$id': {
      id: '/_app/(inventory)/cars/(tabs)/$id'
      path: '/cars/$id'
      fullPath: '/cars/$id'
      preLoaderRoute: typeof AppinventoryCarstabsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(inventory)/cars/(tabs)/$id/': {
      id: '/_app/(inventory)/cars/(tabs)/$id/'
      path: '/'
      fullPath: '/cars/$id/'
      preLoaderRoute: typeof AppinventoryCarstabsIdIndexRouteImport
      parentRoute: typeof AppinventoryCarstabsIdRoute
    }
    '/_app/(inventory)/cars/(tabs)/$id/service-history': {
      id: '/_app/(inventory)/cars/(tabs)/$id/service-history'
      path: '/service-history'
      fullPath: '/cars/$id/service-history'
      preLoaderRoute: typeof AppinventoryCarstabsIdServiceHistoryRouteImport
      parentRoute: typeof AppinventoryCarstabsIdRoute
    }
    '/_app/(inventory)/cars/(tabs)/$id/gallery': {
      id: '/_app/(inventory)/cars/(tabs)/$id/gallery'
      path: '/gallery'
      fullPath: '/cars/$id/gallery'
      preLoaderRoute: typeof AppinventoryCarstabsIdGalleryRouteImport
      parentRoute: typeof AppinventoryCarstabsIdRoute
    }
  }
}

interface AppinventoryCarstabsIdRouteChildren {
  AppinventoryCarstabsIdGalleryRoute: typeof AppinventoryCarstabsIdGalleryRoute
  AppinventoryCarstabsIdServiceHistoryRoute: typeof AppinventoryCarstabsIdServiceHistoryRoute
  AppinventoryCarstabsIdIndexRoute: typeof AppinventoryCarstabsIdIndexRoute
}

const AppinventoryCarstabsIdRouteChildren: AppinventoryCarstabsIdRouteChildren =
  {
    AppinventoryCarstabsIdGalleryRoute: AppinventoryCarstabsIdGalleryRoute,
    AppinventoryCarstabsIdServiceHistoryRoute:
      AppinventoryCarstabsIdServiceHistoryRoute,
    AppinventoryCarstabsIdIndexRoute: AppinventoryCarstabsIdIndexRoute,
  }

const AppinventoryCarstabsIdRouteWithChildren =
  AppinventoryCarstabsIdRoute._addFileChildren(
    AppinventoryCarstabsIdRouteChildren,
  )

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppreportsSalesRoute: typeof AppreportsSalesRoute
  AppbranchesBranchesIdRoute: typeof AppbranchesBranchesIdRoute
  AppinventoryMotorcyclesIdRoute: typeof AppinventoryMotorcyclesIdRoute
  AppbranchesBranchesIndexRoute: typeof AppbranchesBranchesIndexRoute
  AppinventoryCarsIndexRoute: typeof AppinventoryCarsIndexRoute
  AppinventoryMotorcyclesIndexRoute: typeof AppinventoryMotorcyclesIndexRoute
  AppinventoryCarstabsIdRoute: typeof AppinventoryCarstabsIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppreportsSalesRoute: AppreportsSalesRoute,
  AppbranchesBranchesIdRoute: AppbranchesBranchesIdRoute,
  AppinventoryMotorcyclesIdRoute: AppinventoryMotorcyclesIdRoute,
  AppbranchesBranchesIndexRoute: AppbranchesBranchesIndexRoute,
  AppinventoryCarsIndexRoute: AppinventoryCarsIndexRoute,
  AppinventoryMotorcyclesIndexRoute: AppinventoryMotorcyclesIndexRoute,
  AppinventoryCarstabsIdRoute: AppinventoryCarstabsIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicSignInRoute: typeof PublicSignInRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicSignInRoute: PublicSignInRoute,
  PublicSignUpRoute: PublicSignUpRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  InvitationIdRoute: InvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
